# For SCSS-Lint v0.32.0
#https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

linters:

  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BorderZero:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true
    allowed: ^[/* Copyright]

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: false

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: false

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: uppercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  ImportantRule:
    enabled: false

  Indentation:
    enabled: true
    character: space
    width: 4

  LeadingZero:
    enabled: true
    style: include_zero

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: false
    convention: hyphenated_lowercase
    allow_leading_underscore: true

  NestingDepth:
    enabled: false
    max_depth: 3

  PlaceholderInExtend:
    enabled: true

  PropertySpelling:
    enabled: true
    extra_properties: []

  PropertyUnits:
    enabled: false
    global: ['px', '%']

  PseudoElement:
    enabled: false

  QualifyingElement:
    enabled: false
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: false
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: false
    style: double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhiteSpace:
    enabled: true

  TrailingZero:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: false

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true

  VendorPrefixes:
    enabled: true
    identifier_list: base
    include: []
    exclude: []

  ZeroUnit:
    enabled: true

  PropertySortOrder:
    enabled: false
    order:
      - position
      - z-index
      - top
      - right
      - bottom
      - left
      -
      - display
      - visibility
      - float
      - clear
      - overflow
      - overflow-x
      - overflow-y
      - -ms-overflow-x
      - -ms-overflow-y
      - -webkit-overflow-scrolling
      - clip
      - zoom
      - flex-direction
      - flex-order
      - flex-pack
      - flex-align
      -
      - -webkit-box-sizing
      - -moz-box-sizing
      - box-sizing
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      -
      - table-layout
      - empty-cells
      - caption-side
      - border-spacing
      - border-collapse
      - list-style
      - list-style-position
      - list-style-type
      - list-style-image
      -
      - content
      - quotes
      - counter-reset
      - counter-increment
      - resize
      - cursor
      - -webkit-user-select
      - -moz-user-select
      - -ms-user-select
      - user-select
      - nav-index
      - nav-up
      - nav-right
      - nav-down
      - nav-left
      - -webkit-transition
      - -moz-transition
      - -ms-transition
      - -o-transition
      - transition
      - -webkit-transition-delay
      - -moz-transition-delay
      - -ms-transition-delay
      - -o-transition-delay
      - transition-delay
      - -webkit-transition-timing-function
      - -moz-transition-timing-function
      - -ms-transition-timing-function
      - -o-transition-timing-function
      - transition-timing-function
      - -webkit-transition-duration
      - -moz-transition-duration
      - -ms-transition-duration
      - -o-transition-duration
      - transition-duration
      - -webkit-transition-property
      - -moz-transition-property
      - -ms-transition-property
      - -o-transition-property
      - transition-property
      - -webkit-transform
      - -moz-transform
      - -ms-transform
      - -o-transform
      - transform
      - -webkit-transform-origin
      - -moz-transform-origin
      - -ms-transform-origin
      - -o-transform-origin
      - transform-origin
      - -webkit-animation
      - -moz-animation
      - -ms-animation
      - -o-animation
      - animation
      - -webkit-animation-name
      - -moz-animation-name
      - -ms-animation-name
      - -o-animation-name
      - animation-name
      - -webkit-animation-duration
      - -moz-animation-duration
      - -ms-animation-duration
      - -o-animation-duration
      - animation-duration
      - -webkit-animation-play-state
      - -moz-animation-play-state
      - -ms-animation-play-state
      - -o-animation-play-state
      - animation-play-state
      - -webkit-animation-timing-function
      - -moz-animation-timing-function
      - -ms-animation-timing-function
      - -o-animation-timing-function
      - animation-timing-function
      - -webkit-animation-delay
      - -moz-animation-delay
      - -ms-animation-delay
      - -o-animation-delay
      - animation-delay
      - -webkit-animation-iteration-count
      - -moz-animation-iteration-count
      - -ms-animation-iteration-count
      - -o-animation-iteration-count
      - animation-iteration-count
      - -webkit-animation-iteration-count
      - -moz-animation-iteration-count
      - -ms-animation-iteration-count
      - -o-animation-iteration-count
      - animation-iteration-count
      - -webkit-animation-direction
      - -moz-animation-direction
      - -ms-animation-direction
      - -o-animation-direction
      - animation-direction
      - text-align
      - -webkit-text-align-last
      - -moz-text-align-last
      - -ms-text-align-last
      - text-align-last
      - vertical-align
      - white-space
      - text-decoration
      - text-emphasis
      - text-emphasis-color
      - text-emphasis-style
      - text-emphasis-position
      - text-indent
      - -ms-text-justify
      - text-justify
      - text-transform
      - letter-spacing
      - word-spacing
      - -ms-writing-mode
      - text-outline
      - text-transform
      - text-wrap
      - text-overflow
      - -ms-text-overflow
      - text-overflow-ellipsis
      - text-overflow-mode
      - -ms-word-wrap
      - word-wrap
      - word-break
      - -ms-word-break
      - -moz-tab-size
      - -o-tab-size
      - tab-size
      - -webkit-hyphens
      - -moz-hyphens
      - hyphens
      - pointer-events
      -
      - opacity
      - filter:progid:DXImageTransform.Microsoft.Alpha(Opacity
      - -ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha
      - -ms-interpolation-mode
      - color
      - border
      - border-collapse
      - border-width
      - border-style
      - border-color
      - border-top
      - border-top-width
      - border-top-style
      - border-top-color
      - border-right
      - border-right-width
      - border-right-style
      - border-right-color
      - border-bottom
      - border-bottom-width
      - border-bottom-style
      - border-bottom-color
      - border-left
      - border-left-width
      - border-left-style
      - border-left-color
      - -webkit-border-radius
      - -moz-border-radius
      - border-radius
      - -webkit-border-top-left-radius
      - -moz-border-radius-topleft
      - border-top-left-radius
      - -webkit-border-top-right-radius
      - -moz-border-radius-topright
      - border-top-right-radius
      - -webkit-border-bottom-right-radius
      - -moz-border-radius-bottomright
      - border-bottom-right-radius
      - -webkit-border-bottom-left-radius
      - -moz-border-radius-bottomleft
      - border-bottom-left-radius
      - -webkit-border-image
      - -moz-border-image
      - -o-border-image
      - border-image
      - -webkit-border-image-source
      - -moz-border-image-source
      - -o-border-image-source
      - border-image-source
      - -webkit-border-image-slice
      - -moz-border-image-slice
      - -o-border-image-slice
      - border-image-slice
      - -webkit-border-image-width
      - -moz-border-image-width
      - -o-border-image-width
      - border-image-width
      - -webkit-border-image-outset
      - -moz-border-image-outset
      - -o-border-image-outset
      - border-image-outset
      - -webkit-border-image-repeat
      - -moz-border-image-repeat
      - -o-border-image-repeat
      - border-image-repeat
      - outline
      - outline-width
      - outline-style
      - outline-color
      - outline-offset
      - background
      - filter:progid:DXImageTransform.Microsoft.AlphaImageLoader
      - background-color
      - background-image
      - background-repeat
      - background-attachment
      - background-position
      - background-position-x
      - -ms-background-position-x
      - background-position-y
      - -ms-background-position-y
      - -webkit-background-clip
      - -moz-background-clip
      - background-clip
      - background-origin
      - -webkit-background-size
      - -moz-background-size
      - -o-background-size
      - background-size
      - box-decoration-break
      - -webkit-box-shadow
      - -moz-box-shadow
      - box-shadow
      - -webkit-box-shadow
      - -moz-box-shadow
      - box-shadow
      - -webkit-box-shadow
      - -moz-box-shadow
      - box-shadow
      - -webkit-box-shadow
      - -moz-box-shadow
      - box-shadow
      - filter:progid:DXImageTransform.Microsoft.gradient
      - -ms-filter:\\'progid:DXImageTransform.Microsoft.gradient
      - text-shadow
      -
      - font
      - font-family
      - font-size
      - font-weight
      - font-style
      - font-variant
      - font-size-adjust
      - font-stretch
      - font-effect
      - font-emphasize
      - font-emphasize-position
      - font-emphasize-style
      - font-smooth
      - line-height
      - src
    separate_groups: true